# Generated by Django 3.1.7 on 2021-03-21 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksUrlModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, null=True)),
                ('books_data', models.CharField(max_length=5000, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BooksModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=100, null=True, unique=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('authors', models.CharField(max_length=100, null=True)),
                ('published_date', models.CharField(max_length=100, null=True)),
                ('categories', models.CharField(max_length=100, null=True)),
                ('average_rating', models.CharField(max_length=100, null=True)),
                ('ratings_count', models.CharField(max_length=100, null=True)),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
