# Generated by Django 3.0 on 2021-03-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='books_data',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
