# Generated by Django 3.0 on 2021-03-18 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210317_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='books_data',
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='authors',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='average_rating',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='book_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='categories',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='published_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='ratings_count',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='thumbnail',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
