# Generated by Django 3.1.7 on 2021-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_booksmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='authors',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='average_rating',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='book_id',
            field=models.CharField(max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='categories',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='published_date',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='ratings_count',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='thumbnail',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='booksurlmodel',
            name='url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
