# Generated by Django 3.0 on 2021-03-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210318_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='book_id',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
