# Generated by Django 3.0 on 2021-03-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210318_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksmodel',
            name='average_rating',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booksmodel',
            name='ratings_count',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
