# Generated by Django 3.0 on 2021-03-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210318_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksmodel',
            name='books_data',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
